<identifier> ::= <identifier_start> <identifier_part>*

<identifier_start> ::= [A-Za-z_$]
<identifier_part> ::= <identifier_start>  | <digit>
<digit> ::= [0-9]

<program> ::= <import>* <type_definition>*

<import> ::= "import" ( <dart_import> |  <package_import> )
<dart_import> ::= "@" <import_identifier>
<package_import> ::= <import_identifier>
<import_identifier> ::= <identifier> ( "/" <identifier> )*

<type_definition> ::= "type" <identifier> ( "(" <named_type_literal> ( "," <named_type_literal> )* ")" )? "=" <type_variation> ( "+" <type_variation> )*
<type_variant> ::= <identifier> ( "(" <type_variant_parameter> ( "," <type_variant_parameter> )* ")" )?
<type_variant_parameter> ::= <type_literal> <identifier>

<type_literal> ::= <top_type_literal>
		 | <bottom_type_literal>
		 | <list_type_literal>
                 | <set_type_literal>
		 | <map_type_literal>
		 | <parameterized_type_literal>
		 | <named_type_literal>
		 | <option_type_literal>

<top_type_literal> ::= "⊤"
<bottom_type_literal> ::= "⊥"
<list_type_literal> ::= "[" <type_literal> "]"
<set_type_literal> ::= "{" <type_literal> "}"
<map_type_literal> ::= "{" <type_literal> ":" <type_literal> "}"
<parameterized_type_literal> ::= <named_type_literal> ( "(" <type_literal> ( "," <type_literal> )* ")" )
<named_type_literal> ::= <identifier>
<option_type_literal> ::= <type_literal> "?"
