<identifier> ::= <identifier_start> <identifier_part>*

<identifier_start> ::= [A-Za-z_$]
<identifier_part> ::= <identifier_start>  | <digit>
<digit> ::= [0-9]

<program> ::= <type_declaration>*

<type_definition> ::= "type" <identifier> ( "(" <identifier> ( "," <identifier> )* ")" )? "=" <type_variation> ( "+" <type_variation> )*
<type_variation> ::= <identifier> ( "(" <type_variation_parameter> ( "," <type_variation_parameter> )* ")" )?
<type_variation_parameter> ::= <identifier> <identifier>

